name: CI (Windows)

on:
  push:
    paths: ['*']
  pull_request:
    paths: ['*']
  schedule:
    - cron: '0 15 * * *'

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Install Roswell
        shell: bash
        run: |
          curl -L https://github.com/roswell/roswell/releases/download/v19.08.10.101/roswell_19.08.10.101_i686.zip -o roswell.zip
          unzip roswell.zip -d /c/
          /c/roswell/ros setup
      - name: Install Ultralisp
        shell: bash
        run: /c/roswell/ros -e '(ql-dist:install-dist "http://dist.ultralisp.org/" :prompt nil)'
      - name: Install Rove
        shell: bash
        run: /c/roswell/ros install fukamachi/rove
      - name: Install dependencies
        shell: bash
        run: |
          /c/roswell/ros install fukamachi/cl-cookie
      - name: Run tests
        shell: bash
        run: |
          PATH="~/.roswell/bin:$PATH"
          /c/roswell/ros -S . rove dexador-test.asd
