name: CI

on: [push]

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
          ROSWELL_INSTALL_DIR: /usr
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Install Rove
        run: ros install rove
      - name: Install dependencies
        run: |
          ros install fukamachi/clack
          ros install fukamachi/fast-http
      - name: Run tests (Linux, Mac)
        run: |
          PATH="~/.roswell/bin:$PATH"
          rove dexador-test.asd
        if: matrix.os != 'windows-latest'
      - name: Run tests (Windows)
        run: |
          ros %userprofile%\.roswell\bin\rove dexador-test.asd
        if: matrix.os == 'windows-latest'
